### ISSUE TITLE
strings_error.xml localization

### ISSUE THREAD

**Issue by imsyf** [oneHamidreza/Meow-Framework-MVVM#1]
~~How do I go about translating various error messages that you conveniently added to this framework/library to other language, beside Persian?~~

~~Should I just send PR? Would you willing to then push the change to `jcenter`?~~

I didn't realize that it would be as easy as adding new values in my own `strings.xml`. How silly of me.
Please close or even delete this ridiculous "issue".

**Comment by oneHamidreza** [comment]
just place customized `strings_error.xml` into your values folder.

**Comment by imsyf** [comment]
yep, i should've tried it first.

while you're here, is there any plan to add support for paging 3? i think it would be tremendously helpful

**Comment by oneHamidreza** [comment]
Yes . I have plan for it. it will be add to project soon.
